
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_emp_comp_range1
      description: "A starter dbt model"
      columns:
          - name: EMP_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_employee1
      description: "A starter dbt model"
      columns:
          - name: EMP_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          